todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    ToggleAssignToTaskView,
    TaskDeleteView,
    TaskUpdateView,
    CreateTaskView,
    TagsListView,
    CreateTagView,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", CreateTaskView.as_view(), name="task-create"),
    path("tasks/<int:pk>/complete/", ToggleAssignToTaskView.as_view(), name="toggle-complete"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/create/", CreateTagView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo_list_application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("__debug__/", include("debug_toolbar.urls")),
]

todo/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    deadline_datetime = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks", blank=True)

    class Meta:
        ordering = ["-is_done", "created_datetime"]

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )

    class Meta:
        model = Task
        fields = ["content", "deadline_datetime", "tags"]
        widgets = {
            "deadline_datetime": forms.DateTimeInput(
                attrs={'type': 'datetime-local'}
            ),
        }


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ["name"]

todo/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
    CreateView
)

from todo.forms import TaskForm, TagForm
from todo.models import Task, Tag


class TaskListView(ListView):
    queryset = Task.objects.prefetch_related("tags")
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list"] = True
        return context


class CreateTaskView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskDetailView(DetailView):
    model = Task


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class ToggleAssignToTaskView(View):
    def get(self, request, pk):
        task = get_object_or_404(Task, id=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo:task-list")


class TagsListView(ListView):
    queryset = Tag.objects.all()
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list"] = True
        return context


class CreateTagView(CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo:tags-list")


class TagUpdateView(UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo:tags-list")


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tags-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Todo list</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} m-2" role="alert">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
          {% if list %}
            {% block pagination %}
            {% include "includes/pagination.html" %}
            {% endblock %}
          {% endif %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/pagination.html
<div class="col-12 ml-3">
  <span class="step-links">
  {% if page_obj.has_previous %}
  <a href="?page=1">&laquo; first</a>
  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
  {% endif %}
  <span class="current">
  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
  </span>
  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">next</a>
  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
  {% endif %}
  </span>
</div>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group mt-4">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tags-list' %}">Tags</a></li>
</ul>

templates/includes/toggle_complete.html
{% if not task.is_done %}
<button type="button" class="btn btn-success ml-5">
<a href="{% url 'todo:toggle-complete' pk=task.id %}" class="text-white">
  Complete
</a>
</button>
{% else %}
<button type="button" class="btn btn-secondary ml-5">
<a href="{% url 'todo:toggle-complete' pk=task.id %}" class="text-white">
  Undo
</a>
</button>
{% endif %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<div style="padding: 20px">
  <form method="post">{% csrf_token %}
      <h1>Are you sure you want to delete "{{ object }}"?</h1>
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger mt-3" value="Confirm">Danger</button>
  </form>
</div>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div style="padding: 20px">
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
      All Tags <button type="button" class="btn btn-success ml-5">
      <a href="{% url 'todo:tag-create'%}" class="text-white">
      Create tag
      </a>
      </button>
    </h1>
  </div>
  <div class="py-5">
    <div class="row">
      {% for tag in tag_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
              {{tag.name}}
            </h2>
            <br><br>
            <button type="button" class="btn btn-primary">
            <a class="text-white"
              href="{% url 'todo:tag-update' pk=tag.id %}"
              >
            Update
            </a>
            </button>
            <button type="button" class="btn btn-danger">
            <a class="text-white"
              href="{% url 'todo:tag-delete' pk=tag.id %}"
              >
            Delete
            </a>
            </button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/todo/task_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div style="padding: 20px">
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
      All Tasks <button type="button" class="btn btn-success ml-5">
      <a href="{% url 'todo:task-create'%}" class="text-white">
      Create task
      </a>
      </button>
    </h1>
  </div>
  <div class="py-5">
    <div class="row">
      {% for task in task_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
              {{task.content}}
            </h2>
            <h2 style="font-size: 18px; font-weight: bold; min-height: 42px;
              {% if task.is_done %} color: darkgrey;
              {% else %} color: red; {% endif %}"
              >
              {% if task.is_done %} Done {% else %} Not done {% endif %}
              {% include "includes/toggle_complete.html" %}
            </h2>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted">
              Created: {{task.created_datetime}}
              </small>
            </div>
            <small class="text-red" style="color: red">
            Deadline: {{task.deadline_datetime}}
            </small><br>
            <small class="text-muted">Tags: </small>
            {% for tag in task.tags.all %}
            <small class="text-muted">{{ tag }}</small>
            {% endfor %}
            <br><br>
            <button type="button" class="btn btn-primary">
            <a class="text-white"
              href="{% url 'todo:task-update' pk=task.id %}"
              >
            Update
            </a>
            </button>
            <button type="button" class="btn btn-danger">
            <a class="text-white"
              href="{% url 'todo:task-delete' pk=task.id %}"
              >
            Delete
            </a>
            </button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}